SET IDENTITY_INSERT [dbo].[Exercises] ON
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (1, 2, 5, N'Front Cable Raise', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (2, 2, 5, N'Rope Upright Rows', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (3, 1, 5, N'Bench Squats', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (4, 2, 5, N'DB Lateral Raise', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (5, 2, 5, N'DB Arnold Press', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (6, 1, 5, N'Toe Taps', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (7, 2, 5, N'Laying DB Side Raise', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (8, 2, 5, N'Seated "Y" Raise', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (9, 2, 2, N'Assisted Pull Ups', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (10, 2, 2, N'ISO High Lat Row', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (11, 2, 2, N'Rope Face Pulls', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (12, 2, 2, N'Cross Cable Pull Down', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (13, 2, 2, N'1 Arm DB Row', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (14, 2, 2, N'Close Grip Pulldown', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (15, 1, 2, N'Bench Squats', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (16, 2, 3, N'Plate Flys', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (17, 2, 3, N'Smith Mch Press', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (18, 2, 3, N'Incline DB Press', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (19, 2, 3, N'Close Stance Push Ups', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (20, 2, 3, N'Cable Uppercuts', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (21, 2, 3, N'Lay Down DB Flys', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (22, 1, 3, N'Push Ups', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (23, 1, 3, N'Toe Taps', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (24, 2, 1, N'Close Stance Push Up', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (25, 2, 1, N'ISO Dumbbell Curls', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (26, 2, 1, N'1 Arm Cable Kickbacks', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (27, 2, 1, N'Double Bi Cable Curl', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (28, 2, 1, N'Straight Bar Pushdown', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (29, 2, 1, N'Alt Lunges', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (30, 1, 1, N'Pop Squats', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (32, 2, 4, N'Smith Mch Squats', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (33, 2, 4, N'DB Walking Lunges', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (34, 2, 4, N'Hamstring Curls', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (35, 2, 4, N'Glute Kickbacks', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (36, 2, 4, N'Leg Press - Wide', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (37, 2, 4, N'Leg Press - Close', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (38, 1, 4, N'Bench Step Ups', NULL, NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [LabelID], [Name], [Type], [WorkoutID]) VALUES (39, 1, 4, N'Toe Taps', NULL, NULL)
SET IDENTITY_INSERT [dbo].[Exercises] OFF
