SET IDENTITY_INSERT [dbo].[Exercises] ON
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (1, 2, N'Front Cable Raise', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (2, 2, N'Rope Upright Rows', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (4, 2, N'DB Lateral Raise', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (5, 2, N'DB Arnold Press', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (7, 2, N'Laying DB Side Raise', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (8, 2, N'Seated "Y" Raise', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (9, 2, N'Assisted Pull Ups', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (10, 2, N'ISO High Lat Row', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (11, 2, N'Rope Face Pulls', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (12, 2, N'Cross Cable Pull Down', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (13, 2, N'1 Arm DB Row', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (14, 2, N'Close Grip Pulldown', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (15, 1, N'Bench Squats', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (16, 2, N'Plate Flys', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (17, 2, N'Smith Mch Press', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (18, 2, N'Incline DB Press', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (19, 2, N'Close Stance Push Ups', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (20, 2, N'Cable Uppercuts', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (21, 2, N'Lay Down DB Flys', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (22, 1, N'Push Ups', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (25, 2, N'ISO Dumbbell Curls', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (26, 2, N'1 Arm Cable Kickbacks', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (27, 2, N'Double Bi Cable Curl', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (28, 2, N'Straight Bar Pushdown', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (29, 2, N'Alt Lunges', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (30, 1, N'Pop Squats', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (32, 2, N'Smith Mch Squats', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (33, 2, N'DB Walking Lunges', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (34, 2, N'Hamstring Curls', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (35, 2, N'Glute Kickbacks', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (36, 2, N'Leg Press - Wide', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (37, 2, N'Leg Press - Close', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (38, 1, N'Bench Step Ups', NULL)
INSERT INTO [dbo].[Exercises] ([ID], [ExerciseTypeID], [Name], [WorkoutID]) VALUES (39, 1, N'Toe Taps', NULL)
SET IDENTITY_INSERT [dbo].[Exercises] OFF
